[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.kitty]
input_path = "~/Dotfiles/matugen/kitty-template.conf"
output_path = "~/.config/kitty/themes/your-theme.conf"
post_hook = "kitty +kitten themes --reload-in=all your-theme"
