# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a6a67e23-85df-4cb2-9867-51488a3ae81f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a6a67e23-85df-4cb2-9867-51488a3ae81f".device = "/dev/disk/by-uuid/a6a67e23-85df-4cb2-9867-51488a3ae81f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/19E2-A6E8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-35f7e6b3-af08-4617-9b7e-f9503f49a544"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
