#!/bin/sh

cd ~ || exit

# Get japanese input working
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=fcitx

# We're on hyprland
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland

# We're on Wayland
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM=wayland

# Enable application specific wayland envvars
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONPARENTING=1

# Start!
exec hyprland
